version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: escola-app
    restart: always
    expose:
      - "3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=0000
      - DB_NAME=escola_infantil
    networks:
      - escola-network

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: escola-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=escola_infantil
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - escola-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: escola-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - escola-network

networks:
  escola-network:
    driver: bridge

volumes:
  db-data: